version: '3'
networks:
  youlai-boot:
    driver: bridge

services:
  retail-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: retail-api
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /mydata/app/retail-api/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Tokyo
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/youlai_boot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Tokyo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESSKEY=${MINIO_ROOT_USER}
      - MINIO_SECRETKEY=${MINIO_ROOT_PASSWORD}
    networks:
      - youlai-boot
    external_links:
      - youlai-mysql:mysql
      - youlai-redis:redis
      - youlai-minio:minio
      - youlai-rabbitmq:rabbitmq
      - youlai-xxl-job-admin:xxl-job-admin
