server:
  port: 8080
spring:
  application:
    name: ec-backend
services:
  order:
    base-url: ${ORDER_SERVICE_BASE_URL:http://localhost:8081}
  account:
    base-url: ${ACCOUNT_SERVICE_BASE_URL:http://localhost:8082}
